version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app/client
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
    # Points to a file with the sensitive environment variables
    env_file:
      - ./frontend/.env
    ports:
      - 5050:3000
  go-server:
      image: go-server
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: go-server
      working_dir: /app/server
      environment:
        - DB_HOST=postgres-db
      ports:
        - "5000:5000"
      volumes:
        - ./backend:/app/server
        - .env:/app/.env
      depends_on:
        - postgres-db
      entrypoint: go run cmd/main.go
      restart: always
  postgres-db:
    image: postgres:15.5-alpine3.18
    container_name: postgres-db
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d